export const api = {
	LOAD_CART: 'LOAD_CART',
	LOAD_CART_SUCCESS: 'LOAD_CART_SUCCESS',
	LOAD_CART_ERROR: 'LOAD_CART_ERROR',
	ADD_ITEM: 'ADD_ITEM_TO_CART',
	ADD_ITEM_DONE: 'ADD_ITEM_DONE',
	DELETE_ITEM: 'DELETE_ITEM_FROM_CART',
	DELETE_ITEM_DONE: 'DELETE_ITEM_DONE',

	BAGS_PRODUCTS_LOAD : 'BAGS_PRODUCTS_LOAD',
	BAGS_PRODUCTS_LOAD_SUCCESS : 'BAGS_PRODUCTS_LOAD_SUCCESS',
	BAGS_PRODUCTS_LOAD_FAIL : 'BAGS_PRODUCTS_LOAD_FAIL',

	WALLETS_PURSES_PRODUCTS_LOAD : 'WALLETS_PURSES_PRODUCTS_LOAD',
	WALLETS_PURSES_PRODUCTS_LOAD_SUCCESS : 'WALLETS_PURSES_PRODUCTS_LOAD_SUCCESS',
	WALLETS_PURSES_PRODUCTS_LOAD_FAIL : 'WALLETS_PURSES_PRODUCTS_LOAD_FAIL',

	KEYCHAINS_PRODUCTS_LOAD : 'KEYCHAINS_PRODUCTS_LOAD',
	KEYCHAINS_PRODUCTS_LOAD_SUCCESS : 'KEYCHAINS_PRODUCTS_LOAD_SUCCESS',
	KEYCHAINS_PRODUCTS_LOAD_FAIL : 'KEYCHAINS_PRODUCTS_LOAD_FAIL',

	SUNGLASSES_PRODUCTS_LOAD : 'SUNGLASSES_PRODUCTS_LOAD',
	SUNGLASSES_PRODUCTS_LOAD_SUCCESS : 'SUNGLASSES_PRODUCTS_LOAD_SUCCESS',
	SUNGLASSES_PRODUCTS_LOAD_FAIL : 'SUNGLASSES_PRODUCTS_LOAD_FAIL',

	PINS_PRODUCTS_LOAD : 'PINS_PRODUCTS_LOAD',
	PINS_PRODUCTS_LOAD_SUCCESS : 'PINS_PRODUCTS_LOAD_SUCCESS',
	PINS_PRODUCTS_LOAD_FAIL : 'PINS_PRODUCTS_LOAD_FAIL',

	JEWELS_PRODUCTS_LOAD : 'JEWELS_PRODUCTS_LOAD',
	JEWELS_PRODUCTS_LOAD_SUCCESS : 'JEWELS_PRODUCTS_LOAD_SUCCESS',
	JEWELS_PRODUCTS_LOAD_FAIL : 'JEWELS_PRODUCTS_LOAD_FAIL',

	SCARVES_PRODUCTS_LOAD : 'SCARVES_PRODUCTS_LOAD',
	SCARVES_PRODUCTS_LOAD_SUCCESS : 'SCARVES_PRODUCTS_LOAD_SUCCESS',
	SCARVES_PRODUCTS_LOAD_FAIL : 'SCARVES_PRODUCTS_LOAD_FAIL',

	SALE_PRODUCTS_LOAD : 'SALE_PRODUCTS_LOAD',
	SALE_PRODUCTS_LOAD_SUCCESS : 'SALE_PRODUCTS_LOAD_SUCCESS',
	SALE_PRODUCTS_LOAD_FAIL : 'SALE_PRODUCTS_LOAD_FAIL'
}